version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopping_cart
      MYSQL_USER: user123
      MYSQL_PASSWORD: pass123
    ports:
      - 3306:3306
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ./DeployDB/database.sql:/docker-entrypoint-initdb.d/database.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - 8080:8080
    networks:
      - app-network
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=user123
      - DB_PASSWORD=pass123
      - DB_DATABASE=shopping_cart
      - DB_TYPE=mysql
    command: ["sh", "-c", "sleep 20 && /cmd/main"]

networks:
  app-network:
